config/routes.rb
Rails.application.routes.draw do
  resources :teachers
  resources :subjects
  resources :students
  resources :sections
  resources :days
  resources :assitances
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/assitance.rb
class Assitance < ApplicationRecord
  belongs_to :student
end

app/controllers/assitances_controller.rb
class AssitancesController < ApplicationController
  before_action :set_assitance, only: [:show, :edit, :update, :destroy]

  # GET /assitances
  # GET /assitances.json
  def index
    @assitances = Assitance.all
  end

  # GET /assitances/1
  # GET /assitances/1.json
  def show
  end

  # GET /assitances/new
  def new
    @assitance = Assitance.new
  end

  # GET /assitances/1/edit
  def edit
  end

  # POST /assitances
  # POST /assitances.json
  def create
    @assitance = Assitance.new(assitance_params)

    respond_to do |format|
      if @assitance.save
        format.html { redirect_to @assitance, notice: 'Assitance was successfully created.' }
        format.json { render :show, status: :created, location: @assitance }
      else
        format.html { render :new }
        format.json { render json: @assitance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /assitances/1
  # PATCH/PUT /assitances/1.json
  def update
    respond_to do |format|
      if @assitance.update(assitance_params)
        format.html { redirect_to @assitance, notice: 'Assitance was successfully updated.' }
        format.json { render :show, status: :ok, location: @assitance }
      else
        format.html { render :edit }
        format.json { render json: @assitance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /assitances/1
  # DELETE /assitances/1.json
  def destroy
    @assitance.destroy
    respond_to do |format|
      format.html { redirect_to assitances_url, notice: 'Assitance was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_assitance
      @assitance = Assitance.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def assitance_params
      params.require(:assitance).permit(:assitance_present, :student_id)
    end
end

app/helpers/assitances_helper.rb
module AssitancesHelper
end

app/views/assitances/_form.html.erb
<%= form_for(assitance) do |f| %>
  <% if assitance.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(assitance.errors.count, "error") %> prohibited this assitance from being saved:</h2>

      <ul>
      <% assitance.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :assitance_present %>
    <%= f.number_field :assitance_present %>
  </div>

  <div class="field">
    <%= f.label :student_id %>
    <%= f.text_field :student_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/assitances/edit.html.erb
<h1>Editing Assitance</h1>

<%= render 'form', assitance: @assitance %>

<%= link_to 'Show', @assitance %> |
<%= link_to 'Back', assitances_path %>

app/views/assitances/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Assitances</h1>

<table>
  <thead>
    <tr>
      <th>Assitance present</th>
      <th>Student</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @assitances.each do |assitance| %>
      <tr>
        <td><%= assitance.assitance_present %></td>
        <td><%= assitance.student %></td>
        <td><%= link_to 'Show', assitance %></td>
        <td><%= link_to 'Edit', edit_assitance_path(assitance) %></td>
        <td><%= link_to 'Destroy', assitance, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Assitance', new_assitance_path %>

app/views/assitances/new.html.erb
<h1>New Assitance</h1>

<%= render 'form', assitance: @assitance %>

<%= link_to 'Back', assitances_path %>

app/views/assitances/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Assitance present:</strong>
  <%= @assitance.assitance_present %>
</p>

<p>
  <strong>Student:</strong>
  <%= @assitance.student %>
</p>

<%= link_to 'Edit', edit_assitance_path(@assitance) %> |
<%= link_to 'Back', assitances_path %>